---

- name: Update
  shell: sudo apt update

- name: Set the root password 
  mysql_user: login_user=root login_password="" user=root password="snipeit1"

- name: Secure the root user for IPV6 localhost (::1)
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="::1"

- name: Secure the root user for IPV4 localhost (127.0.0.1)
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="127.0.0.1"

- name: Secure the root user for localhost domain
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="localhost"

- name: Secure the root user for server_hostname domain
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="{{ ansible_fqdn }}"

- name: Deletes anonymous server user
  mysql_user: login_user=root login_password="snipeit1" user="" host_all=yes state=absent

- name: Removes the test database
  mysql_db: login_user=root login_password="snipeit1" db=test state=absent
