---
  - name: PHP
    apt: name=software-properties-common

  - name: Add co-installable PHP 7.2
    apt_repository: 
     repo: 'ppa:ondrej/php'

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  - name: Install PHP Extensions and PyMysql
    apt: name={{item}} state=latest
    with_items:
      - php7.2
      - libapache2-mod-php7.2
      - php7.2-common
      - php7.2-gmp
      - php7.2-curl
      - php7.2-intl
      - php7.2-mbstring
      - php7.2-xmlrpc
      - php7.2-mysql
      - php7.2-gd
      - php7.2-bcmath
      - php7.2-xml
      - php7.2-cli
      - php7.2-zip
      - php7.2-sqlite3
      - php7.2-ldap
      - python-mysqldb
